language: c

compiler:
  - clang
  - gcc

sudo: required

services:
  - docker

env:
  global:
    # DEPLOY_USER
    - secure: "2JfHAUTxw/dV+7bZc5PpNVnV0aisBra15RzKepS4MOfHghOZQfsbClvOWQrNPumY0Gm42b9/AxqngRXIRQCZDRHpFL3NDAxQEMdKl1feh3ycgS3MhBTWuN5z37vhHEcOSS1eEo9S20pej2hCrxijZ+3fm2eD4hrBH/wQ+wpRsboEmPZk0J9mJccTX6GnNndcnDoJVUYMbIS3S7T1AQYANBJPgO/cIhXgoQJF1V/soLc8rcRqm1OwcLMT8gbZjGMGmgVTCll/XU0XZZGuiKu3YKIzpM1gt/5aeC5YsDpCEP5bkAI7AXzyhWiZwjmWWh5qdhohxkyTQZ6rRx6KmFk5zTb3CeroJWWzMjozJM/VrkCNMJSrBqS2VimugODe23CClYRUOpwNMj5NUW9gxNFWQmafQ1IHPWz9KAwVRg4QIgPrQuWhygHz60QD3R1LXzGFlww8O7kS26wrT5fg0+j5iSHIPqUoCMMVEMRZiKVcAxiCg2NrClU3bPN3oUJ/kuQ60OzPUkj/7hK+M3MMHjq38JXm13hqpPt2mM5rI+caV++04NaGFDN3XpHHJEG4eFdHg1G1H3SAYWFQU11wpdBlYRYJd+UKdy9qCx8VEto+2CdQk+BjDk1LfQrOdYAZHagthJwlHQuIRUQ3taSiipFyWfR3tltCXzv8urF30h0dSwk="
    # DEPLOY_HOST
    - secure: "kAPgAZ/QN8gDUnag3NttH3kZphT3lO9g3xmZW7Pp4b72Dx9RJ58MdUULbIF/khuitxxVhqAAnsJLuPEfqKR8y2dRcZhKxypfrGRxve9erdDdyj0HHhd/IeGPyS3wqcrTj0RbE8sRpR9m+gT5IdcnAENAVIBULTAOfyt6wqEWhyZ8mcRlGvSgvOKC07aZfWpQsGuyDOBOa9b1RGJqSYDkPJca94O4TVSUayDhJt3ZzVnpmZ6mFm62cFpzYMoMrw7xGXzj+INM6PseCbwbAGITGgFeo7jb8Zh4P4NfuAIOrH6HsvQAiYRJKYvTghTdkiEIL6k8OZRHPJGXr7qd6PGbCjOD/eYu3aaDM7TEQCrYR+9uHSpOL7gvcyKkRpUm9FF5XKxudK7owJ6CSmq5FSY+uOyCky0NipBp8LK9/oILXBcgaIFJFK9zz9SdBYm30se2iRxqiVf+2vVWewmHhV5sqJ+g2RjJblUt8QNv5Uo+OM+x/oOdrQzFJtWWDuZDA+Z3zoD4YwfT4XwmRYlUWI2naCd7rnFQEpzcwH4GU35Vux9C2iH9snrMKZTseQCoQKW+Eo74AeHfdtdzPsPMeQAzch3A91rhyW0NLSatqTuPSCGkC+sTrgW4qh6RBipuYc62mGINlHZD6kmS5BB58JmM4g1fAx5TXBZzVb3+zmvmlNA="

arch:
  artifacts:
    - qbs-shared-artifacts.tar.gz
  packages:
    - qbs
    - qt5-declarative
    - glib2
    #- clazy-git
    - xorg-server-xvfb
  script:
    - export CLAZY_CHECKS="level1"
    - qbs-setup-toolchains --detect
    - qbs-setup-qt /usr/bin/qmake-qt5 qt5
    - qbs config profiles.qt5.baseProfile ${CC}
    - eval `dbus-launch --sh-syntax` && xvfb-run -a -s "-screen 0 800x600x24" qbs build -d build -j $(nproc) --all-products profile:qt5 modules.qbs.installRoot:/ modules.lirideployment.prefix:/usr

script:
  - "curl -s https://raw.githubusercontent.com/lirios/repotools/develop/travis/docker-travis.sh | bash"

deploy:
  - provider: script
    script: .travis/deploy.sh build/default/qtgsettings-artifacts.tar.gz
    skip_cleanup: true
    on:
      branch: master
      condition: "$CC = gcc) && ($TRAVIS_PULL_REQUEST = false"
  - provider: script
    script: .travis/deploy.sh build/default/qtgsettings-artifacts.tar.gz
    skip_cleanup: true
    on:
      branch: develop
      condition: "$CC = gcc) && ($TRAVIS_PULL_REQUEST = false"

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
