language: c

compiler:
  - clang
  - gcc

sudo: required

env:
  global:
    # BINTRAY_USER
    - secure: "q66TV+gUPMjRjjAVuuo+CXvs67EDL8KrV2IQ/MVE0P+WPMw8tdIjWqdvHFD7t/5Uw19QJAZvvo3eDK4Eg5D3cJcQU6KcWAmS1Dw8dNKsAl3dlV33hTjb3YYbewzvoYIKOkjMh2r9fXGwDdiuct+J0ZRIGT1xVbWB8pe9TCIRrFnHfnJdj0pfxeswv0se4NZaMbMau0GWzs3tjuOZ/OmZtl63zOgABGPkAq8PTEtArNkRm3Rv9uawftBjbyjn6Ic9NmapP3JxZKOI8NpRNUor7a4pZJ29K3EdM0NQGRVevDTcXeaF0WgHGH3Wh5ousVOu125yODbOcqRZ2jMpdtjm9eyhtG0mfFqXljI7D5FwvrL6CYXBZSV0pAPcD0QetHB8sbzD6n+9tftl2yaoRmfun8loDqcd5pTkYgVxQeGJto03z2XjaSvGLfBReuPnYc+Ztg1k154HDr5O9SNHIgjXLhNVvJE/ezTbC9DH10dTfAJ+5ngeO2E2rUaktbOKbRlvONPcF6sr/lQ0UccPUqNaZjvdHgZ5o1eqU+99WEo/RjS6yt35BQ8D2z8W1FAXr3x3mYKJGq3j62cnXZxYnDMf/2R1cKBUvbS3Tk4DrmPa7tjGSkrWFo+kbGF73XhrTb1az3wYl+FK3Wlzcw0urcqJe4pjJweWGUimbWE7EMDrdjw="
    # BINTRAY_API_KEY
    - secure: "heujTdQ3QirqMGgWJgd9wZB/tsadlzl/vwr4jPB6ZSfmrFNlJq9PbxCju19EIvEPT/qVleWv4+ZBxLcI9xkavX75+xvLr4bs++yXtbSdGRNdDzkV9idkWPwYC1Gy6hamOF+ZbP9Z8Z42Y30OVflTRt5Nar5bee25/RtL1eIc+fUPkpD5B67Pd+2L5gQwfU9tebABojwMP9qtiNNllwxsBZ7OTcfI9L0M5TTN30uL345NPTTVCW38QvDrTyyPeRxVyFc8SPttiJJ5m/kjuhFBHYnZzItE9K+2wLJq5H2UerUXKS7qKAJGHa0VK/g/pptVbKGzh3YWVnnQzHissrWnq//8nQ4XImyBV2FXAGE77KTrDHPcUdfFkITeWFLJgKJvx0oMLl19H1clyVFEpLpmx+4XD4VqOro+LiGJZPQZ8RAnWMove6vyUrwQVi9yYhrakPCVMZt05eQU6aN5pBH5VStNQRdEYc7GJvVAHBtYDCzzsGPW+JEOdj/z4dj3inRj+sbVh4EUNnVetaNqCk4SzoFY0XR2N3W/OEM4k23r8d4ondmMFSSRQc1Nj6jHQDoRxgcRg6RbcGvfEFQbq92sCWzdxunq1QoBRNE2hmc2+TP9cwR73tW4h+kmUTk2Z4CD+TD6msnyPF5XA9Y5GT//opBxvCD6FKH+WHhSzRgNl6k="
    # BINTRAY_REPO_OWNER
    - secure: "ZjkIBhwXPQDc3RpfbWzNIw1WA36pQvVSn19ZnPMIUWmU2xy6YWcNUuk56A/5JAcbcGv3yPqWyMfJzFyJDuQzqWCFlEOZWB0NB4Kw3TdyPCimzslS7JOlC8qq3xfFx3B0/CVwhz1G4jzBKL5H/asF4PGcoaZwGNg21tGMM8yegbNrKm+QC9AGfABhJdTQzSn+CzSXMItF3E4N7oBPe0mlq1i1x65jVXVIDMUVeGmm+wz1nMUFRRzqlGgpoger4TKb93ZoxHrt1TPqdwdYm+CrCY8L3/lXDNYM3ezYgxO3jlNbWu/yPgE/u/Wjl0P+MZr54jT6uoEY1bWKBC4U4sQY+c9w5o4ZRKVjpyiamnZPsxRdC3i+HHdbDOIheRYSGboFE+Hlf/x1TfY6IQY/e+2Ob92c2otj8mTrqWAumZ+yhhqKdP0Ci3r+uDzSybToqY8cnvvyDUIwefoQH/78HkxYpWTHiCSR70R0JetSXAykDXF36FGXbKavAYBLE8I04p/1G/P8jjr6kLhwV1YNL2U24fGa/3RryebzcOEmbfNeSVcP36DGgfMOaImf+QCetp2/J429syplkl1SE4o0KxljS970T36+GcSrwK6i9L/Lfqq836gjJ53PQmRd5svmrvUnaFZ3j2Lb7I2C37R+VQo7+/dB+P/0uIc8N/altMbydKk="

arch:
  packages:
    - qt5-declarative
    - glib2
    - clang
    #- clazy-git
    - xorg-server-xvfb
  script:
    - export CLAZY_CHECKS="level1"
    - mkdir build
    - if [ "$CC" = "gcc" ]; then cd build && qmake -spec linux-g++ CONFIG+=use_qt_paths ../qtgsettings.pro; fi
    #- if [ "$CC" = "clang" ]; then cd build && qmake -spec linux-clang CONFIG+=use_qt_paths QMAKE_CXX="clazy" ../qtgsettings.pro; fi
    - if [ "$CC" = "clang" ]; then cd build && qmake -spec linux-clang CONFIG+=use_qt_paths ../qtgsettings.pro; fi
    - cd build && make -j$(nproc)
    - cd build && xvfb-run -a -s "-screen 0 800x600x24" make check
    - ./.travis/bintray-wrapper.sh

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

deploy:
  provider: bintray
  on:
    branch: develop
    condition: "$CC = gcc"
  file: cibuild/bintray.json
  user:
    secure: "dcMhE0W1Ecy1RGJpfUcpsDaF5dnFFLemTRzz68bxNk2zakM3aBBMjnpqFHwXUQgxj3Xhnxx2pyh61Oc36aFQ4Aw1hmfRNn7C7vch6VA8tlNoJLgmR50NKyOnjCRKZo478crdKvEZey2i1nP3iBa61hD1iWwJg+3XZ89W4wnGmVnSDpI05/rb9iUXSFLliZV2c9a4cmptZHvqN1PuBHTeEtr5A9SPWT9cR6PfzcVUYnWqUVk/PG3FKL+GkA9Qj/Fj1nuDIMzrqCKPUAqW1a1h/AO7YXn1kNLgUPk3cQngDkmukMBzjrqsnoYD24eXwnRsQhiJfYyBBr4cawSa/GzWyT65NCJuVvr147XSj/eMHSS8dU2xOQamVwdi1AMixTKeXq17z3gTI8bSOMj7kaYz3GEHJhDHM2DV8lYpaJ7thh6W1H6bNxYOj06sTMKxdh+4rhBLpJBFb6hMm3P/RBdz1ZkBYceakcG3l3amlZNpaWYTKBjicHs96tQ1g9JbL/OFhlFqwp4H/IIGRaBzvCy+GJMhTz9PVAd9hbA8kNCZ9IYFDQGJTIFUx7eFbbks1XJcWLOG6yNW8ywfvtEAr2obWigVytFS6jD7xDUlkHjSluY0IHkXRoB22+tMxpXZ+8y4szow3aABJ8pIWGSRJU3P9wNQFUGepdv3N+yZUMMqK2o="
  key:
    secure: "TgUvT02pmz475NLu4VgwMy0UNsg/vrAM1XhYyBpwjDt/PjIkS/Vvf6aiH9RqahmfkeiQPy0KGXelUvcQeqrrmHl/jaJwT312BLgAqzeXKbVzJmX97Jyw2zyYFjGQQ81cUI08y7ZLVCju1zt+xD9HZWAxgFEbvy5AqoZTZjXLjyXU2xeo6VPy9pHKgmXM8DIs1FvzdDelksOvZMaZrVvT5KE4CgD+9sXWdhRBb9pnNEm/sg0DOIUv41cNpqKsXnTfbEJrSwVbcWWvdnFt5fblMRpOl/4nfQIDvWd3KDJBqKl2RW47YxJ50dX+b2khL1vxbqJPunZdjsm1yphZECtfMvBEjegBGUuyQ3KKcDw+yDHZ1BSfwdN+3Ta6Z1okcfsLhkNVMa6RWnfuhr6pnRf1gPWlYfiZX1lvPvHp45bGWAq/Vx3AVr63tbhNN6COk/cZgUfemdX8PPb+KHtGTsl4+4BgvtlxZUluw0GalWr5A4bjNDyy4+6VKePotGI4Ta4LgSxG8TQqyx4WUzSNkTMBZlSz8d4gdYaxoCpPRTYvhYVvxd1IKybRJ0P2Y5cEuevVojGQCnXikTYuBcb47qDQdJEGGgJ8LTRevqz3FdHHVb+Xk1xlRTs6ADYyuNcEs9j+2/Xp6jSe5GsALc7NU/zX49VidQyDuXfxlcs6PnWTVe4="

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
